### ISSUE TITLE
how can I adjust the format of my input data?

### ISSUE THREAD

**Issue by lixiaoyi-12** [jimmyyhwu/deepsea#1]
Sorry to bother you for this quite stupid. I'm new to machine learning and TensorFlow. I want to train the DeepSEA model by myself to make the model better fit my dataset for prediction. I noticed that the training data you downloaded have already been in .mat format, but currently my dataset is the .bed file (containing the chromosome, start and end coordinate, score with tab delimited) downloaded from ENCODE. Could you please tell me how to convert my data to mat format? That will help me a lot!

**Comment by jimmyyhwu** [comment]
I directly used the .mat format. You would probably need to contact the DeepSEA authors for the conversion details.
